name: Build Xrm Plugin
 
on:
  create:
    tags:
      - 'v*'
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code

    # Marketplace Action to setup the PATH to have the MSBuild toolset in the path 
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore DLaB.Xrm.FilterPlugin.sln
 
    - name: Build and Publish Web App
      run: msbuild DLaB.Xrm.FilterPlugin.sln
 
    - name: Release
      uses: anton-yurchenko/git-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "false"
        CHANGELOG_FILE: "none"
        ALLOW_EMPTY_CHANGELOG: "true"
        ALLOW_TAG_PREFIX: "true"
      with:
        args: |
            build\\DLaB.Xrm.Filter.Plugins\bin\Debug\DLaB.Xrm.Filter.Plugins.dll
